-- =============================================================================
-- Seed: País, Departamentos y Municipios de Guatemala
-- Ejecutar en: Supabase → SQL Editor
-- =============================================================================

DO $$
DECLARE
  v_seed UUID        := '00000000-0000-0000-0000-000000000001';
  v_now  TIMESTAMPTZ := now();
BEGIN

-- ─── PAÍS ──────────────────────────────────────────────────────────────────

INSERT INTO cartera.t_pais (codigo, nombre, agrego_usuario, agrego_fecha, modifico_usuario, modifico_fecha)
VALUES ('GT', 'GUATEMALA', v_seed, v_now, v_seed, v_now)
ON CONFLICT DO NOTHING;

-- ─── DEPARTAMENTOS ─────────────────────────────────────────────────────────

INSERT INTO cartera.t_departamento (pais, codigo, nombre, agrego_usuario, agrego_fecha, modifico_usuario, modifico_fecha)
VALUES
  ('GT', '1',  'GUATEMALA',        v_seed, v_now, v_seed, v_now),
  ('GT', '2',  'EL PROGRESO',      v_seed, v_now, v_seed, v_now),
  ('GT', '3',  'SACATEPEQUEZ',     v_seed, v_now, v_seed, v_now),
  ('GT', '4',  'CHIMALTENANGO',    v_seed, v_now, v_seed, v_now),
  ('GT', '5',  'ESCUINTLA',        v_seed, v_now, v_seed, v_now),
  ('GT', '6',  'SANTA ROSA',       v_seed, v_now, v_seed, v_now),
  ('GT', '7',  'SOLOLA',           v_seed, v_now, v_seed, v_now),
  ('GT', '8',  'TOTONICAPAN',      v_seed, v_now, v_seed, v_now),
  ('GT', '9',  'QUETZALTENANGO',   v_seed, v_now, v_seed, v_now),
  ('GT', '10', 'SUCHITEPEQUEZ',    v_seed, v_now, v_seed, v_now),
  ('GT', '11', 'RETALHULEU',       v_seed, v_now, v_seed, v_now),
  ('GT', '12', 'SAN MARCOS',       v_seed, v_now, v_seed, v_now),
  ('GT', '13', 'HUEHUETENANGO',    v_seed, v_now, v_seed, v_now),
  ('GT', '14', 'QUICHE',           v_seed, v_now, v_seed, v_now),
  ('GT', '15', 'BAJA VERAPAZ',     v_seed, v_now, v_seed, v_now),
  ('GT', '16', 'ALTA VERAPAZ',     v_seed, v_now, v_seed, v_now),
  ('GT', '17', 'PETEN',            v_seed, v_now, v_seed, v_now),
  ('GT', '18', 'IZABAL',           v_seed, v_now, v_seed, v_now),
  ('GT', '19', 'ZACAPA',           v_seed, v_now, v_seed, v_now),
  ('GT', '20', 'CHIQUIMULA',       v_seed, v_now, v_seed, v_now),
  ('GT', '21', 'JALAPA',           v_seed, v_now, v_seed, v_now),
  ('GT', '22', 'JUTIAPA',          v_seed, v_now, v_seed, v_now)
ON CONFLICT DO NOTHING;

-- ─── MUNICIPIOS ────────────────────────────────────────────────────────────

INSERT INTO cartera.t_municipio (pais, departamento, codigo, nombre, agrego_usuario, agrego_fecha, modifico_usuario, modifico_fecha)
VALUES
  -- GUATEMALA (1)
  ('GT','1','1',  'GUATEMALA',                    v_seed,v_now,v_seed,v_now),
  ('GT','1','2',  'SANTA CATARINA PINULA',         v_seed,v_now,v_seed,v_now),
  ('GT','1','3',  'SAN JOSE PINULA',               v_seed,v_now,v_seed,v_now),
  ('GT','1','4',  'SAN JOSE DEL GOLFO',            v_seed,v_now,v_seed,v_now),
  ('GT','1','5',  'PALENCIA',                      v_seed,v_now,v_seed,v_now),
  ('GT','1','6',  'CHINAUTLA',                     v_seed,v_now,v_seed,v_now),
  ('GT','1','7',  'SAN PEDRO AYAMPUC',             v_seed,v_now,v_seed,v_now),
  ('GT','1','8',  'MIXCO',                         v_seed,v_now,v_seed,v_now),
  ('GT','1','9',  'SAN PEDRO SACATEPEQUEZ',        v_seed,v_now,v_seed,v_now),
  ('GT','1','10', 'SAN JUAN SACATEPEQUEZ',         v_seed,v_now,v_seed,v_now),
  ('GT','1','11', 'SAN RAYMUNDO',                  v_seed,v_now,v_seed,v_now),
  ('GT','1','12', 'CHUARRANCHO',                   v_seed,v_now,v_seed,v_now),
  ('GT','1','13', 'FRAIJANES',                     v_seed,v_now,v_seed,v_now),
  ('GT','1','14', 'AMATITLAN',                     v_seed,v_now,v_seed,v_now),
  ('GT','1','15', 'VILLA NUEVA',                   v_seed,v_now,v_seed,v_now),
  ('GT','1','16', 'VILLA CANALES',                 v_seed,v_now,v_seed,v_now),
  ('GT','1','17', 'SAN MIGUEL PETAPA',             v_seed,v_now,v_seed,v_now),
  -- EL PROGRESO (2)
  ('GT','2','1',  'GUASTATOYA',                    v_seed,v_now,v_seed,v_now),
  ('GT','2','2',  'MORAZAN',                       v_seed,v_now,v_seed,v_now),
  ('GT','2','3',  'SAN AGUSTIN ACASAGUASTLAN',     v_seed,v_now,v_seed,v_now),
  ('GT','2','4',  'SAN CRISTOBAL ACASAGUASTLAN',   v_seed,v_now,v_seed,v_now),
  ('GT','2','5',  'EL JICARO',                     v_seed,v_now,v_seed,v_now),
  ('GT','2','6',  'SANSARE',                       v_seed,v_now,v_seed,v_now),
  ('GT','2','7',  'SANARATE',                      v_seed,v_now,v_seed,v_now),
  ('GT','2','8',  'SAN ANTONIO LA PAZ',            v_seed,v_now,v_seed,v_now),
  -- SACATEPEQUEZ (3)
  ('GT','3','1',  'ANTIGUA GUATEMALA',             v_seed,v_now,v_seed,v_now),
  ('GT','3','2',  'JOCOTENANGO',                   v_seed,v_now,v_seed,v_now),
  ('GT','3','3',  'PASTORES',                      v_seed,v_now,v_seed,v_now),
  ('GT','3','4',  'SUMPANGO',                      v_seed,v_now,v_seed,v_now),
  ('GT','3','5',  'SANTO DOMINGO XENACOJ',         v_seed,v_now,v_seed,v_now),
  ('GT','3','6',  'SANTIAGO SACATEPEQUEZ',         v_seed,v_now,v_seed,v_now),
  ('GT','3','7',  'SAN BARTOLOME MILPAS ALTAS',    v_seed,v_now,v_seed,v_now),
  ('GT','3','8',  'SAN LUCAS SACATEPEQUEZ',        v_seed,v_now,v_seed,v_now),
  ('GT','3','9',  'SANTA LUCIA MILPAS ALTAS',      v_seed,v_now,v_seed,v_now),
  ('GT','3','10', 'MAGDALENA MILPAS ALTAS',        v_seed,v_now,v_seed,v_now),
  ('GT','3','11', 'SANTA MARIA DE JESUS',          v_seed,v_now,v_seed,v_now),
  ('GT','3','12', 'CIUDAD VIEJA',                  v_seed,v_now,v_seed,v_now),
  ('GT','3','13', 'SAN MIGUEL DUEÑAS',             v_seed,v_now,v_seed,v_now),
  ('GT','3','14', 'SAN JUAN ALOTENANGO',           v_seed,v_now,v_seed,v_now),
  ('GT','3','15', 'SAN ANTONIO AGUAS CALIENTES',   v_seed,v_now,v_seed,v_now),
  ('GT','3','16', 'SANTA CATARINA BARAHONA',       v_seed,v_now,v_seed,v_now),
  -- CHIMALTENANGO (4)
  ('GT','4','1',  'CHIMALTENANGO',                 v_seed,v_now,v_seed,v_now),
  ('GT','4','2',  'SAN JOSE POAQUIL',              v_seed,v_now,v_seed,v_now),
  ('GT','4','3',  'SAN MARTIN JILOTEPEQUE',        v_seed,v_now,v_seed,v_now),
  ('GT','4','4',  'SAN JUAN COMALAPA',             v_seed,v_now,v_seed,v_now),
  ('GT','4','5',  'SANTA APOLONIA',                v_seed,v_now,v_seed,v_now),
  ('GT','4','6',  'TECPAN GUATEMALA',              v_seed,v_now,v_seed,v_now),
  ('GT','4','7',  'PATZUN',                        v_seed,v_now,v_seed,v_now),
  ('GT','4','8',  'SAN MIGUEL POCHUTA',            v_seed,v_now,v_seed,v_now),
  ('GT','4','9',  'PATZICIA',                      v_seed,v_now,v_seed,v_now),
  ('GT','4','10', 'SANTA CRUZ BALANYA',            v_seed,v_now,v_seed,v_now),
  ('GT','4','11', 'ACATENANGO',                    v_seed,v_now,v_seed,v_now),
  ('GT','4','12', 'SAN PEDRO YEPOCAPA',            v_seed,v_now,v_seed,v_now),
  ('GT','4','13', 'SAN ANDRES ITZAPA',             v_seed,v_now,v_seed,v_now),
  ('GT','4','14', 'PARRAMOS',                      v_seed,v_now,v_seed,v_now),
  ('GT','4','15', 'ZARAGOZA',                      v_seed,v_now,v_seed,v_now),
  ('GT','4','16', 'EL TEJAR',                      v_seed,v_now,v_seed,v_now),
  -- ESCUINTLA (5)
  ('GT','5','1',  'ESCUINTLA',                     v_seed,v_now,v_seed,v_now),
  ('GT','5','2',  'SANTA LUCIA COTZUMALGUAPA',     v_seed,v_now,v_seed,v_now),
  ('GT','5','3',  'LA DEMOCRACIA',                 v_seed,v_now,v_seed,v_now),
  ('GT','5','4',  'SIQUINALA',                     v_seed,v_now,v_seed,v_now),
  ('GT','5','5',  'MASAGUA',                       v_seed,v_now,v_seed,v_now),
  ('GT','5','6',  'TIQUISATE',                     v_seed,v_now,v_seed,v_now),
  ('GT','5','7',  'LA GOMERA',                     v_seed,v_now,v_seed,v_now),
  ('GT','5','8',  'GUANAGAZAPA',                   v_seed,v_now,v_seed,v_now),
  ('GT','5','9',  'PUERTO DE SAN JOSE',            v_seed,v_now,v_seed,v_now),
  ('GT','5','10', 'IZTAPA',                        v_seed,v_now,v_seed,v_now),
  ('GT','5','11', 'PALIN',                         v_seed,v_now,v_seed,v_now),
  ('GT','5','12', 'SAN VICENTE PACAYA',            v_seed,v_now,v_seed,v_now),
  ('GT','5','13', 'NUEVA CONCEPCION',              v_seed,v_now,v_seed,v_now),
  -- SANTA ROSA (6)
  ('GT','6','1',  'CUILAPA',                       v_seed,v_now,v_seed,v_now),
  ('GT','6','2',  'BARBERENA',                     v_seed,v_now,v_seed,v_now),
  ('GT','6','3',  'SANTA ROSA DE LIMA',            v_seed,v_now,v_seed,v_now),
  ('GT','6','4',  'CASILLAS',                      v_seed,v_now,v_seed,v_now),
  ('GT','6','5',  'SAN RAFAEL LAS FLORES',         v_seed,v_now,v_seed,v_now),
  ('GT','6','6',  'ORATORIO',                      v_seed,v_now,v_seed,v_now),
  ('GT','6','7',  'SAN JUAN TECUACO',              v_seed,v_now,v_seed,v_now),
  ('GT','6','8',  'CHIQUIMULILLA',                 v_seed,v_now,v_seed,v_now),
  ('GT','6','9',  'TAXISCO',                       v_seed,v_now,v_seed,v_now),
  ('GT','6','10', 'SANTA MARIA IXHUATAN',          v_seed,v_now,v_seed,v_now),
  ('GT','6','11', 'GUAZACAPAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','6','12', 'SANTA CRUZ NARANJO',            v_seed,v_now,v_seed,v_now),
  ('GT','6','13', 'PUEBLO NUEVO VIÑAS',            v_seed,v_now,v_seed,v_now),
  ('GT','6','14', 'NUEVA SANTA ROSA',              v_seed,v_now,v_seed,v_now),
  -- SOLOLA (7)
  ('GT','7','1',  'SOLOLA',                        v_seed,v_now,v_seed,v_now),
  ('GT','7','2',  'SAN JOSE CHACAYA',              v_seed,v_now,v_seed,v_now),
  ('GT','7','3',  'SANTA MARIA VISITACION',        v_seed,v_now,v_seed,v_now),
  ('GT','7','4',  'SANTA LUCIA UTATLAN',           v_seed,v_now,v_seed,v_now),
  ('GT','7','5',  'NAHUALA',                       v_seed,v_now,v_seed,v_now),
  ('GT','7','6',  'SANTA CATARINA IXTAHUACAN',     v_seed,v_now,v_seed,v_now),
  ('GT','7','7',  'SANTA CLARA LA LAGUNA',         v_seed,v_now,v_seed,v_now),
  ('GT','7','8',  'CONCEPCION',                    v_seed,v_now,v_seed,v_now),
  ('GT','7','9',  'SAN ANDRES SEMETABAJ',          v_seed,v_now,v_seed,v_now),
  ('GT','7','10', 'PANAJACHEL',                    v_seed,v_now,v_seed,v_now),
  ('GT','7','11', 'SANTA CATARINA PALOPO',         v_seed,v_now,v_seed,v_now),
  ('GT','7','12', 'SAN ANTONIO PALOPO',            v_seed,v_now,v_seed,v_now),
  ('GT','7','13', 'SAN LUCAS TOLIMAN',             v_seed,v_now,v_seed,v_now),
  ('GT','7','14', 'SANTA CRUZ LA LAGUNA',          v_seed,v_now,v_seed,v_now),
  ('GT','7','15', 'SAN PABLO LA LAGUNA',           v_seed,v_now,v_seed,v_now),
  ('GT','7','16', 'SAN MARCOS LA LAGUNA',          v_seed,v_now,v_seed,v_now),
  ('GT','7','17', 'SAN JUAN LA LAGUNA',            v_seed,v_now,v_seed,v_now),
  ('GT','7','18', 'SAN PEDRO LA LAGUNA',           v_seed,v_now,v_seed,v_now),
  ('GT','7','19', 'SANTIAGO ATITLAN',              v_seed,v_now,v_seed,v_now),
  -- TOTONICAPAN (8)
  ('GT','8','1',  'TOTONICAPAN',                   v_seed,v_now,v_seed,v_now),
  ('GT','8','2',  'SAN CRISTOBAL TOTONICAPAN',     v_seed,v_now,v_seed,v_now),
  ('GT','8','3',  'SAN FRANCISCO EL ALTO',         v_seed,v_now,v_seed,v_now),
  ('GT','8','4',  'SAN ANDRES XECUL',              v_seed,v_now,v_seed,v_now),
  ('GT','8','5',  'MOMOSTENANGO',                  v_seed,v_now,v_seed,v_now),
  ('GT','8','6',  'SANTA MARIA CHIQUIMULA',        v_seed,v_now,v_seed,v_now),
  ('GT','8','7',  'SANTA LUCIA LA REFORMA',        v_seed,v_now,v_seed,v_now),
  ('GT','8','8',  'SAN BARTOLO AGUAS CALIENTES',   v_seed,v_now,v_seed,v_now),
  -- QUETZALTENANGO (9)
  ('GT','9','1',  'QUETZALTENANGO',                v_seed,v_now,v_seed,v_now),
  ('GT','9','2',  'SALCAJA',                       v_seed,v_now,v_seed,v_now),
  ('GT','9','3',  'OLINTEPEQUE',                   v_seed,v_now,v_seed,v_now),
  ('GT','9','4',  'SAN CARLOS SIJA',               v_seed,v_now,v_seed,v_now),
  ('GT','9','5',  'SIBILIA',                       v_seed,v_now,v_seed,v_now),
  ('GT','9','6',  'CABRICAN',                      v_seed,v_now,v_seed,v_now),
  ('GT','9','7',  'CAJOLA',                        v_seed,v_now,v_seed,v_now),
  ('GT','9','8',  'SAN MIGUEL SIGUILCA',           v_seed,v_now,v_seed,v_now),
  ('GT','9','9',  'SAN JUAN OSTUNCALCO',           v_seed,v_now,v_seed,v_now),
  ('GT','9','10', 'SAN MATEO',                     v_seed,v_now,v_seed,v_now),
  ('GT','9','11', 'CONCEPCION CHIQUIRICHAPA',      v_seed,v_now,v_seed,v_now),
  ('GT','9','12', 'SAN MARTIN SACATEPEQUEZ',       v_seed,v_now,v_seed,v_now),
  ('GT','9','13', 'ALMOLONGA',                     v_seed,v_now,v_seed,v_now),
  ('GT','9','14', 'CANTEL',                        v_seed,v_now,v_seed,v_now),
  ('GT','9','15', 'HUITAN',                        v_seed,v_now,v_seed,v_now),
  ('GT','9','16', 'ZUNIL',                         v_seed,v_now,v_seed,v_now),
  ('GT','9','17', 'COLOMBA',                       v_seed,v_now,v_seed,v_now),
  ('GT','9','18', 'SAN FRANCISCO LA UNION',        v_seed,v_now,v_seed,v_now),
  ('GT','9','19', 'EL PALMAR',                     v_seed,v_now,v_seed,v_now),
  ('GT','9','20', 'COATEPEQUE',                    v_seed,v_now,v_seed,v_now),
  ('GT','9','21', 'GENOVA',                        v_seed,v_now,v_seed,v_now),
  ('GT','9','22', 'FLORES COSTA CUCA',             v_seed,v_now,v_seed,v_now),
  ('GT','9','23', 'LA ESPERANZA',                  v_seed,v_now,v_seed,v_now),
  ('GT','9','24', 'PALESTINA DE LOS ALTOS',        v_seed,v_now,v_seed,v_now),
  -- SUCHITEPEQUEZ (10)
  ('GT','10','1',  'MAZATENANGO',                  v_seed,v_now,v_seed,v_now),
  ('GT','10','2',  'CUYOTENANGO',                  v_seed,v_now,v_seed,v_now),
  ('GT','10','3',  'SAN FRANCISCO ZAPOTITLAN',     v_seed,v_now,v_seed,v_now),
  ('GT','10','4',  'SAN BERNARDINO',               v_seed,v_now,v_seed,v_now),
  ('GT','10','5',  'SAN JOSE EL IDOLO',            v_seed,v_now,v_seed,v_now),
  ('GT','10','6',  'SANTO DOMINGO SUCHITEPEQUEZ',  v_seed,v_now,v_seed,v_now),
  ('GT','10','7',  'SAN LORENZO',                  v_seed,v_now,v_seed,v_now),
  ('GT','10','8',  'SAMAYAC',                      v_seed,v_now,v_seed,v_now),
  ('GT','10','9',  'SAN PABLO JOCOPILAS',          v_seed,v_now,v_seed,v_now),
  ('GT','10','10', 'SAN ANTONIO SUCHITEPEQUEZ',    v_seed,v_now,v_seed,v_now),
  ('GT','10','11', 'SAN MIGUEL PANAN',             v_seed,v_now,v_seed,v_now),
  ('GT','10','12', 'SAN GABRIEL',                  v_seed,v_now,v_seed,v_now),
  ('GT','10','13', 'CHICACAO',                     v_seed,v_now,v_seed,v_now),
  ('GT','10','14', 'PATULUL',                      v_seed,v_now,v_seed,v_now),
  ('GT','10','15', 'SANTA BARBARA',                v_seed,v_now,v_seed,v_now),
  ('GT','10','16', 'SAN JUAN BAUTISTA',            v_seed,v_now,v_seed,v_now),
  ('GT','10','17', 'SANTO TOMAS LA UNION',         v_seed,v_now,v_seed,v_now),
  ('GT','10','18', 'ZUNILITO',                     v_seed,v_now,v_seed,v_now),
  ('GT','10','19', 'PUEBLO NUEVO SUCHITEPEQUEZ',   v_seed,v_now,v_seed,v_now),
  ('GT','10','20', 'RIO BRAVO',                    v_seed,v_now,v_seed,v_now),
  -- RETALHULEU (11)
  ('GT','11','1',  'RETALHULEU',                   v_seed,v_now,v_seed,v_now),
  ('GT','11','2',  'SAN SEBASTIAN',                v_seed,v_now,v_seed,v_now),
  ('GT','11','3',  'SANTA CRUZ MULUA',             v_seed,v_now,v_seed,v_now),
  ('GT','11','4',  'SAN MARTIN ZAPOTITLAN',        v_seed,v_now,v_seed,v_now),
  ('GT','11','5',  'SAN FELIPE RETALHULEU',        v_seed,v_now,v_seed,v_now),
  ('GT','11','6',  'SAN ANDRES VILLA SECA',        v_seed,v_now,v_seed,v_now),
  ('GT','11','7',  'CHAMPERICO',                   v_seed,v_now,v_seed,v_now),
  ('GT','11','8',  'NUEVO SAN CARLOS',             v_seed,v_now,v_seed,v_now),
  ('GT','11','9',  'EL ASINTAL',                   v_seed,v_now,v_seed,v_now),
  -- SAN MARCOS (12)
  ('GT','12','1',  'SAN MARCOS',                   v_seed,v_now,v_seed,v_now),
  ('GT','12','2',  'SAN PEDRO SACATEPEQUEZ',       v_seed,v_now,v_seed,v_now),
  ('GT','12','3',  'SAN ANTONIO SACATEPEQUEZ',     v_seed,v_now,v_seed,v_now),
  ('GT','12','4',  'COMITANCILLO',                 v_seed,v_now,v_seed,v_now),
  ('GT','12','5',  'SAN MIGUEL IXTAHUACAN',        v_seed,v_now,v_seed,v_now),
  ('GT','12','6',  'CONCEPCION TUTUAPA',           v_seed,v_now,v_seed,v_now),
  ('GT','12','7',  'TACANA',                       v_seed,v_now,v_seed,v_now),
  ('GT','12','8',  'SIBINAL',                      v_seed,v_now,v_seed,v_now),
  ('GT','12','9',  'TAJUMULCO',                    v_seed,v_now,v_seed,v_now),
  ('GT','12','10', 'TEJUTLA',                      v_seed,v_now,v_seed,v_now),
  ('GT','12','11', 'SAN RAFAEL PIE DE LA CUESTA',  v_seed,v_now,v_seed,v_now),
  ('GT','12','12', 'NUEVO PROGRESO',               v_seed,v_now,v_seed,v_now),
  ('GT','12','13', 'EL TUMBADOR',                  v_seed,v_now,v_seed,v_now),
  ('GT','12','14', 'SAN JOSE EL RODEO',            v_seed,v_now,v_seed,v_now),
  ('GT','12','15', 'MALACATAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','12','16', 'CATARINA',                     v_seed,v_now,v_seed,v_now),
  ('GT','12','17', 'AYUTLA',                       v_seed,v_now,v_seed,v_now),
  ('GT','12','18', 'OCOS',                         v_seed,v_now,v_seed,v_now),
  ('GT','12','19', 'SAN PABLO',                    v_seed,v_now,v_seed,v_now),
  ('GT','12','20', 'EL QUETZAL',                   v_seed,v_now,v_seed,v_now),
  ('GT','12','21', 'LA REFORMA',                   v_seed,v_now,v_seed,v_now),
  ('GT','12','22', 'PAJAPITA',                     v_seed,v_now,v_seed,v_now),
  ('GT','12','23', 'IXCHIGUAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','12','24', 'SAN JOSE OJETENAN',            v_seed,v_now,v_seed,v_now),
  ('GT','12','25', 'SAN CRISTOBAL CUCHO',          v_seed,v_now,v_seed,v_now),
  ('GT','12','26', 'SIPACAPA',                     v_seed,v_now,v_seed,v_now),
  ('GT','12','27', 'ESQUIPULAS PALO GORDO',        v_seed,v_now,v_seed,v_now),
  ('GT','12','28', 'RIO BLANCO',                   v_seed,v_now,v_seed,v_now),
  ('GT','12','29', 'SAN LORENZO',                  v_seed,v_now,v_seed,v_now),
  -- HUEHUETENANGO (13)
  ('GT','13','1',  'HUEHUETENANGO',                v_seed,v_now,v_seed,v_now),
  ('GT','13','2',  'CHIANTLA',                     v_seed,v_now,v_seed,v_now),
  ('GT','13','3',  'MALACATANCITO',                v_seed,v_now,v_seed,v_now),
  ('GT','13','4',  'CUILCO',                       v_seed,v_now,v_seed,v_now),
  ('GT','13','5',  'NENTON',                       v_seed,v_now,v_seed,v_now),
  ('GT','13','6',  'SAN PEDRO NECTA',              v_seed,v_now,v_seed,v_now),
  ('GT','13','7',  'JACALTENANGO',                 v_seed,v_now,v_seed,v_now),
  ('GT','13','8',  'SAN PEDRO SOLOMA',             v_seed,v_now,v_seed,v_now),
  ('GT','13','9',  'SAN ILDELFONSO IXTAHUACAN',    v_seed,v_now,v_seed,v_now),
  ('GT','13','10', 'SANTA BARBARA',                v_seed,v_now,v_seed,v_now),
  ('GT','13','11', 'LA LIBERTAD',                  v_seed,v_now,v_seed,v_now),
  ('GT','13','12', 'LA DEMOCRACIA',                v_seed,v_now,v_seed,v_now),
  ('GT','13','13', 'SAN MIGUEL ACATAN',            v_seed,v_now,v_seed,v_now),
  ('GT','13','14', 'SAN RAFAEL LA INDEPENDENCIA',  v_seed,v_now,v_seed,v_now),
  ('GT','13','15', 'TODOS SANTOS CHUCHCUMATAN',    v_seed,v_now,v_seed,v_now),
  ('GT','13','16', 'SAN JUAN ATITAN',              v_seed,v_now,v_seed,v_now),
  ('GT','13','17', 'SANTA EULALIA',                v_seed,v_now,v_seed,v_now),
  ('GT','13','18', 'SAN MATEO IXTATAN',            v_seed,v_now,v_seed,v_now),
  ('GT','13','19', 'COLOTENANGO',                  v_seed,v_now,v_seed,v_now),
  ('GT','13','20', 'SAN SEBASTIAN HUEHUETENANGO',  v_seed,v_now,v_seed,v_now),
  ('GT','13','21', 'TECTITAN',                     v_seed,v_now,v_seed,v_now),
  ('GT','13','22', 'CONCEPCION HUISTA',            v_seed,v_now,v_seed,v_now),
  ('GT','13','23', 'SAN JUAN IXCOY',               v_seed,v_now,v_seed,v_now),
  ('GT','13','24', 'SAN ANTONIO HUISTA',           v_seed,v_now,v_seed,v_now),
  ('GT','13','25', 'SAN SEBASTIAN COATAN',         v_seed,v_now,v_seed,v_now),
  ('GT','13','26', 'SANTA CRUZ BARILLAS',          v_seed,v_now,v_seed,v_now),
  ('GT','13','27', 'AGUACATAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','13','28', 'SAN RAFAEL PETZAL',            v_seed,v_now,v_seed,v_now),
  ('GT','13','29', 'SAN GASPAR IXCHIL',            v_seed,v_now,v_seed,v_now),
  ('GT','13','30', 'SANTIAGO CHIMALTENANGO',       v_seed,v_now,v_seed,v_now),
  ('GT','13','31', 'SANTA ANA HUISTA',             v_seed,v_now,v_seed,v_now),
  -- QUICHE (14)
  ('GT','14','1',  'SANTA CRUZ DEL QUICHE',        v_seed,v_now,v_seed,v_now),
  ('GT','14','2',  'CHICHE',                       v_seed,v_now,v_seed,v_now),
  ('GT','14','3',  'CHINIQUE',                     v_seed,v_now,v_seed,v_now),
  ('GT','14','4',  'ZACUALPA',                     v_seed,v_now,v_seed,v_now),
  ('GT','14','5',  'CHAJUL',                       v_seed,v_now,v_seed,v_now),
  ('GT','14','6',  'SANTO TOMAS CHICHICASTENANGO', v_seed,v_now,v_seed,v_now),
  ('GT','14','7',  'PATZITE',                      v_seed,v_now,v_seed,v_now),
  ('GT','14','8',  'SAN ANTONIO ILOTENANGO',       v_seed,v_now,v_seed,v_now),
  ('GT','14','9',  'SAN PEDRO JOCOPILAS',          v_seed,v_now,v_seed,v_now),
  ('GT','14','10', 'CUNEN',                        v_seed,v_now,v_seed,v_now),
  ('GT','14','11', 'SAN JUAN COTZAL',              v_seed,v_now,v_seed,v_now),
  ('GT','14','12', 'JOYABAJ',                      v_seed,v_now,v_seed,v_now),
  ('GT','14','13', 'SANTA MARIA NEBAJ',            v_seed,v_now,v_seed,v_now),
  ('GT','14','14', 'SAN ANDRES SAJCABAJA',         v_seed,v_now,v_seed,v_now),
  ('GT','14','15', 'SAN MIGUEL USPATAN',           v_seed,v_now,v_seed,v_now),
  ('GT','14','16', 'SACAPULAS',                    v_seed,v_now,v_seed,v_now),
  ('GT','14','17', 'SAN BARTOLOME JOCOTENANGO',    v_seed,v_now,v_seed,v_now),
  ('GT','14','18', 'CANILLA',                      v_seed,v_now,v_seed,v_now),
  ('GT','14','19', 'CHICAMAN',                     v_seed,v_now,v_seed,v_now),
  ('GT','14','20', 'PLAYA GRANDE - IXCAN',         v_seed,v_now,v_seed,v_now),
  ('GT','14','21', 'PACHALUM',                     v_seed,v_now,v_seed,v_now),
  -- BAJA VERAPAZ (15)
  ('GT','15','1',  'SALAMA',                       v_seed,v_now,v_seed,v_now),
  ('GT','15','2',  'SAN MIGUEL CHICAJ',            v_seed,v_now,v_seed,v_now),
  ('GT','15','3',  'RABINAL',                      v_seed,v_now,v_seed,v_now),
  ('GT','15','4',  'CUBULCO',                      v_seed,v_now,v_seed,v_now),
  ('GT','15','5',  'GRANADOS',                     v_seed,v_now,v_seed,v_now),
  ('GT','15','6',  'SANTA CRUZ EL CHOL',           v_seed,v_now,v_seed,v_now),
  ('GT','15','7',  'SAN JERONIMO',                 v_seed,v_now,v_seed,v_now),
  ('GT','15','8',  'PURULHA',                      v_seed,v_now,v_seed,v_now),
  -- ALTA VERAPAZ (16)
  ('GT','16','1',  'COBAN',                        v_seed,v_now,v_seed,v_now),
  ('GT','16','2',  'SANTA CRUZ VERAPAZ',           v_seed,v_now,v_seed,v_now),
  ('GT','16','3',  'SAN CRISTOBAL VERAPAZ',        v_seed,v_now,v_seed,v_now),
  ('GT','16','4',  'TACTIC',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','5',  'TAMAHU',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','6',  'SAN MIGUEL TUCURU',            v_seed,v_now,v_seed,v_now),
  ('GT','16','7',  'PANZOS',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','8',  'SENAHU',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','9',  'SAN PEDRO CARCHA',             v_seed,v_now,v_seed,v_now),
  ('GT','16','10', 'SAN JUAN CHAMELCO',            v_seed,v_now,v_seed,v_now),
  ('GT','16','11', 'LANQUIN',                      v_seed,v_now,v_seed,v_now),
  ('GT','16','12', 'SANTA MARIA CAHABON',          v_seed,v_now,v_seed,v_now),
  ('GT','16','13', 'CHISEC',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','14', 'CHAHAL',                       v_seed,v_now,v_seed,v_now),
  ('GT','16','15', 'FRAY BARTOLOME DE LAS CASAS',  v_seed,v_now,v_seed,v_now),
  ('GT','16','16', 'SANTA CATARINA LA TINTA',      v_seed,v_now,v_seed,v_now),
  -- PETEN (17)
  ('GT','17','1',  'FLORES',                       v_seed,v_now,v_seed,v_now),
  ('GT','17','2',  'SAN JOSE',                     v_seed,v_now,v_seed,v_now),
  ('GT','17','3',  'SAN BENITO',                   v_seed,v_now,v_seed,v_now),
  ('GT','17','4',  'SAN ANDRES',                   v_seed,v_now,v_seed,v_now),
  ('GT','17','5',  'LA LIBERTAD',                  v_seed,v_now,v_seed,v_now),
  ('GT','17','6',  'SAN FRANCISCO',                v_seed,v_now,v_seed,v_now),
  ('GT','17','7',  'SANTA ANA',                    v_seed,v_now,v_seed,v_now),
  ('GT','17','8',  'DOLORES',                      v_seed,v_now,v_seed,v_now),
  ('GT','17','9',  'SAN LUIS',                     v_seed,v_now,v_seed,v_now),
  ('GT','17','10', 'SAYAXCHE',                     v_seed,v_now,v_seed,v_now),
  ('GT','17','11', 'MELCHOR DE MENCOS',            v_seed,v_now,v_seed,v_now),
  ('GT','17','12', 'POPTUN',                       v_seed,v_now,v_seed,v_now),
  -- IZABAL (18)
  ('GT','18','1',  'PUERTO BARRIOS',               v_seed,v_now,v_seed,v_now),
  ('GT','18','2',  'LIVINGSTON',                   v_seed,v_now,v_seed,v_now),
  ('GT','18','3',  'EL ESTOR',                     v_seed,v_now,v_seed,v_now),
  ('GT','18','4',  'MORALES',                      v_seed,v_now,v_seed,v_now),
  ('GT','18','5',  'LOS AMATES',                   v_seed,v_now,v_seed,v_now),
  -- ZACAPA (19)
  ('GT','19','1',  'ZACAPA',                       v_seed,v_now,v_seed,v_now),
  ('GT','19','2',  'ESTANZUELA',                   v_seed,v_now,v_seed,v_now),
  ('GT','19','3',  'RIO HONDO',                    v_seed,v_now,v_seed,v_now),
  ('GT','19','4',  'GUALAN',                       v_seed,v_now,v_seed,v_now),
  ('GT','19','5',  'TECULUTAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','19','6',  'USUMATLAN',                    v_seed,v_now,v_seed,v_now),
  ('GT','19','7',  'CABAÑAS',                      v_seed,v_now,v_seed,v_now),
  ('GT','19','8',  'SAN DIEGO',                    v_seed,v_now,v_seed,v_now),
  ('GT','19','9',  'LA UNION',                     v_seed,v_now,v_seed,v_now),
  ('GT','19','10', 'HUITE',                        v_seed,v_now,v_seed,v_now),
  -- CHIQUIMULA (20)
  ('GT','20','1',  'CHIQUIMULA',                   v_seed,v_now,v_seed,v_now),
  ('GT','20','2',  'SAN JOSE LA ARADA',            v_seed,v_now,v_seed,v_now),
  ('GT','20','3',  'SAN JUAN HERMITA',             v_seed,v_now,v_seed,v_now),
  ('GT','20','4',  'JOCOTAN',                      v_seed,v_now,v_seed,v_now),
  ('GT','20','5',  'CAMOTAN',                      v_seed,v_now,v_seed,v_now),
  ('GT','20','6',  'OLOPA',                        v_seed,v_now,v_seed,v_now),
  ('GT','20','7',  'ESQUIPULAS',                   v_seed,v_now,v_seed,v_now),
  ('GT','20','8',  'CONCEPCION LAS MINAS',         v_seed,v_now,v_seed,v_now),
  ('GT','20','9',  'QUEZALTEPEQUE',                v_seed,v_now,v_seed,v_now),
  ('GT','20','10', 'SAN JACINTO',                  v_seed,v_now,v_seed,v_now),
  ('GT','20','11', 'IPALA',                        v_seed,v_now,v_seed,v_now),
  -- JALAPA (21)
  ('GT','21','1',  'JALAPA',                       v_seed,v_now,v_seed,v_now),
  ('GT','21','2',  'SAN PEDRO PINULA',             v_seed,v_now,v_seed,v_now),
  ('GT','21','3',  'SAN LUIS JILOTEPEQUE',         v_seed,v_now,v_seed,v_now),
  ('GT','21','4',  'SAN MANUEL CHAPARRON',         v_seed,v_now,v_seed,v_now),
  ('GT','21','5',  'SAN CARLOS ALZATATE',          v_seed,v_now,v_seed,v_now),
  ('GT','21','6',  'MONJAS',                       v_seed,v_now,v_seed,v_now),
  ('GT','21','7',  'MATAQUESCUINTLA',              v_seed,v_now,v_seed,v_now),
  -- JUTIAPA (22)
  ('GT','22','1',  'JUTIAPA',                      v_seed,v_now,v_seed,v_now),
  ('GT','22','2',  'EL PROGRESO',                  v_seed,v_now,v_seed,v_now),
  ('GT','22','3',  'SANTA CATARINA MITA',          v_seed,v_now,v_seed,v_now),
  ('GT','22','4',  'AGUA BLANCA',                  v_seed,v_now,v_seed,v_now),
  ('GT','22','5',  'ASUNCION MITA',                v_seed,v_now,v_seed,v_now),
  ('GT','22','6',  'YUPILTEPEQUE',                 v_seed,v_now,v_seed,v_now),
  ('GT','22','7',  'ATESCATEMPA',                  v_seed,v_now,v_seed,v_now),
  ('GT','22','8',  'JEREZ',                        v_seed,v_now,v_seed,v_now),
  ('GT','22','9',  'EL ADELANTO',                  v_seed,v_now,v_seed,v_now),
  ('GT','22','10', 'ZAPOTITLAN',                   v_seed,v_now,v_seed,v_now),
  ('GT','22','11', 'COMAPA',                       v_seed,v_now,v_seed,v_now),
  ('GT','22','12', 'JALPATAGUA',                   v_seed,v_now,v_seed,v_now),
  ('GT','22','13', 'CONGUACO',                     v_seed,v_now,v_seed,v_now),
  ('GT','22','14', 'MOYUTA',                       v_seed,v_now,v_seed,v_now),
  ('GT','22','15', 'PASACO',                       v_seed,v_now,v_seed,v_now),
  ('GT','22','16', 'SAN JOSE ACATEMPA',            v_seed,v_now,v_seed,v_now),
  ('GT','22','17', 'QUEZADA',                      v_seed,v_now,v_seed,v_now)
ON CONFLICT DO NOTHING;

END $$;

-- Verificación
SELECT 'Paises'       AS tabla, COUNT(*) AS total FROM cartera.t_pais
UNION ALL
SELECT 'Departamentos', COUNT(*) FROM cartera.t_departamento
UNION ALL
SELECT 'Municipios',    COUNT(*) FROM cartera.t_municipio;
